project:
  type: website

website:
  title: "World Populism Dataset"
  description: "World Populism Dataset"
  site-url: "https://worldpopulism.org/"

  repo-url: https://github.com/World-Populism-Dataset/
  repo-actions: []
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://shiny.nectric.com.au/wpd-app/
        text: App
      - data.qmd
      - notes.qmd
    right:
      - icon: download
        text: Downloads
        menu:
          - text: All data
            href: '#'
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/World-Populism-Dataset/

format:
  html:
    css: styles.css
    theme: cosmo-dark
    toc: true
    page-layout: full


